# -*- coding: utf-8 -*-

{
    'name': 'Job Card Extension',
    'category': 'Services/Project',
    'version': '18.0.1.1.0',
    'author': 'Sarasoft',
    'company': '',
    'maintainer': 'Sarasoft',
    'website': '',
    'summary': 'Job Card Extension',
    'images': [],
    'description': "Job Card Extension",
    'depends': ['project', 'job_card', 'base', 'account', 'board', 'fleet', 'sale', 'sale_project', 'stock',
                'auto_account_setup',  'garage_management_odoo', 'product', 'hr_timesheet','post_dated_cheque_mgt_app',
                'odex_coupon_management', 'hr_expense'],
    'data': [
        'data/account_data.xml',
        'data/job_card_stage_data.xml',
        'security/ir.model.access.csv',
        'wizard/jobcard_advance_payment.xml',
        # 'security/security.xml',
        # 'views/customer_declaration.xml',
        'views/product_template_view.xml',
        'views/project_view.xml',
        'views/job_card_stage_view.xml',
        'views/job_card_views.xml',
        'views/res_partner_views.xml',
        # 'views/account_report.xml',
        # 'views/job_card_dashboard.xml',
        # 'views/job_card_payment_views.xml',
        'views/timesheet_views.xml',
        # 'views/sale_order_views.xml',
        'views/account_move_view.xml',
        # 'reports/account_insurance_invoice_report_job.xml',
        # 'views/account_move_vendor_bill_view.xml',
        # 'views/material_purchase_requisition_views.xml',
        'views/fleet_vehicle_views.xml',
        'views/repair_sub_category_views.xml',
        'views/job_card_bay_view.xml',
        # 'views/account_payment_views.xml',
        'views/res_company_views.xml',
        'views/purchase_order_view.xml',
        'views/purchase_multi_rfq.xml',
        'views/hr_expense_view.xml',
        'reports/action_report.xml',
        'reports/job_card_report_tmpl.xml',
        'reports/account_invoice_report_tmpl.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'job_card_extension/static/src/vehicle_condition/vehicle_condition.scss',
            'job_card_extension/static/src/vehicle_condition/vehicle_condition.js',
            'job_card_extension/static/src/vehicle_condition/vehicle_condition.xml',
        ],
        'web.assets_qweb': [
            'job_card_extension/static/xml/**/*.xml',
        ],
    },

    'demo': [],
    'license': 'AGPL-3',
    'installable': True,
    'application': False,
    'auto_install': False,
}
