from . import res_company
from . import booking_service_type
from . import booking_working_hours
from . import booking_holiday
from . import booking_location
from . import booking_slot
from . import booking_availability
from . import booking_schedule_day
from . import booking_schedule
from . import booking_booking
from . import booking_reschedule
from . import fleet_vehicle
from . import res_partner
from . import res_config_settings
from . import res_users
