from . import mail_ai
from . import ai_prompt_template
from . import mail_thread
from . import discuss_channel
from . import mail_message
from . import res_partner
from . import ai_assistant
from . import ai_message
from . import ai_thread
